FROM python:3.12-slim

WORKDIR /app

# Instalar dependencias del sistema, como LibreOffice y dependencias para buildear psycopg2 si aplica
RUN apt-get update && apt-get install -y \
    libreoffice \
    libpq-dev gcc \
    --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# Usamos Gunicorn para servir la app WSGI en producción
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "config.wsgi:application"]
