# Generated by Django 5.0.14 on 2026-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='nombre', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, db_column='descripcion', null=True)),
            ],
            options={
                'db_table': 'permisos',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroCreacionUsuario',
            fields=[
                ('id', models.BigAutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('username_usuario', models.CharField(db_column='username_usuario', max_length=50)),
                ('nombre_usuario', models.CharField(db_column='nombre_usuario', max_length=200)),
                ('email_usuario', models.CharField(db_column='email_usuario', max_length=150)),
                ('rol_asignado', models.CharField(db_column='rol_asignado', max_length=50)),
                ('fecha_creacion', models.DateField(db_column='fecha_creacion')),
                ('hora_creacion', models.TimeField(db_column='hora_creacion')),
                ('estado_creacion', models.CharField(db_column='estado_creacion', max_length=30)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', null=True)),
            ],
            options={
                'db_table': 'registro_creacion_usuario',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre_rol', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, db_column='descripcion', null=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(db_column='id_rol_permiso', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rol_permiso',
                'ordering': ['role__name', 'permission__code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=50, unique=True)),
                ('email', models.CharField(db_column='email', max_length=150, unique=True)),
                ('password_hash', models.TextField(db_column='password_hash')),
                ('nombres', models.CharField(db_column='nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, db_column='direccion', null=True)),
                ('ruta_foto_perfil', models.TextField(blank=True, db_column='ruta_foto_perfil', null=True)),
                ('estado', models.CharField(db_column='estado', max_length=30)),
                ('fecha_creacion', models.DateTimeField(db_column='fecha_creacion')),
            ],
            options={
                'db_table': 'usuarios',
                'ordering': ['username'],
                'managed': False,
            },
        ),
    ]
