# Generated by Django 5.0.14 on 2026-05-12 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('prestamo', 'Préstamo'), ('pago', 'Pago'), ('cliente', 'Cliente'), ('asesor', 'Asesor'), ('garantia', 'Garantía'), ('caja', 'Caja Fuerte'), ('sistema', 'Sistema'), ('mora', 'Mora')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.usuario')),
            ],
            options={
                'db_table': 'bitacora',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
